<?

# jalal7h@gmail.com
# 2015/10/21
# Version 1.0.0

/*
$xl = array(
	0 => array(
		'data 01',
		'data 02',
		'data 03',
	),
	1 => array(
		'data 11',
		'data 12',
		'data 13',
	),
);
include 'modules/PHPExcel/Excel.php';
ExcelExport( $xl );
die();
*/

include 'PHPExcel.php';

function ExcelExport( $xl ){
    
    $objPHPExcel = new PHPExcel();
    
    $objPHPExcel->getProperties()->setCreator("ThinkPHP")
                ->setLastModifiedBy("Daniel Schlichtholz")
                ->setTitle("Office 2007 XLSX Test Document")
                ->setSubject("Office 2007 XLSX Test Document")
                ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
                ->setKeywords("office 2007 openxml php")
                ->setCategory("Test result file");
    $objPHPExcel->getActiveSheet()->setTitle('Minimalistic demo');

    // Set the active Excel worksheet to sheet 0 
    $objPHPExcel->setActiveSheetIndex(0);  

    // Initialise the Excel row number 
    $rowCount = 1;  

    //start of printing column names as names of MySQL fields  
    $column = 'A';

    for ($i = 0; $i <sizeof($xl[0]); $i++){
        $objPHPExcel->getActiveSheet()->setCellValue($column.$rowCount, $xl[0][$i] );
        $column++;
    }

    //end of adding column names  
    //start while loop to get data  
    $rowCount = 2;  
    while( $row = $xl[$rowCount-1] ){  
        $column = 'A';
        for($j=0; $j<sizeof($xl[$rowCount-1]); $j++){  
            if(!isset($row[$j])){  
                $value = NULL;  
            } else if ($row[$j] != ""){
                $value = strip_tags($row[$j]);
            } else {
                $value = "";
            }

            $objPHPExcel->getActiveSheet()->setCellValue($column.$rowCount, $value);
            $column++;
        }
        $rowCount++;
    } 

    // Redirect output to a client’s web browser (Excel5) 
    header('Content-Type: application/vnd.ms-excel'); 
    header('Content-Disposition: attachment;filename="list-of-products.xlsx"'); 
    header('Cache-Control: max-age=0'); 
    // $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5'); 
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
    $objWriter->save('php://output');
}

function ExcelImport( $path_to_excel_file ){
    $objReader = new PHPExcel_Reader_Excel2007();
    $objPHPExcel = $objReader->load( $path_to_excel_file );
    $rowIterator = $objPHPExcel->getActiveSheet()->getRowIterator();

    $skip_rows = 0;
    $excell_array_data = array();
    foreach($rowIterator as $row){
        $cellIterator = $row->getCellIterator();
        $cellIterator->setIterateOnlyExistingCells(false);
        if($skip_rows >= $row->getRowIndex ()) continue;
        $rowIndex = $row->getRowIndex ();
        $excell_array_data[$rowIndex] = array();

        foreach ($cellIterator as $cell) {
            $excell_array_data[$rowIndex][$cell->getColumn()] = $cell->getCalculatedValue();
        }
    }

    // the fields 
    $columns_name = array();
    $columns_name = $excell_array_data[$skip_rows+1];
    foreach (array_keys($columns_name) as $fieldname ){
        $rw[] = $fieldname;
    }
    $xl[] = $rw;

    // the data
    foreach( $excell_array_data as $k=>$v_arr){
        $rw = null;
        foreach($v_arr as $alphabet => $value){
            $rw[] = $value;
        }
        $xl[] = $rw;
    }

    return $xl;
}



